name = "gnoga"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Wayne Bullaughey"]
maintainers = ["Wayne Bullaughey <wlb122@verizon.net>"]
maintainers-logins = ["wbullaughey"]
[[depends-on]]
gnatcoll = "^23.0.0"

[[depends-on]]
ada_lib = "*"

[[pins]]
ada_lib  = { path = "../../../ada_lib" }


