name = "gnoga"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""

project-files = "gnoga.gpr"

tags = []

[[depends-on]]
alr_environment = "~0.1.0-dev"

[[pins]]
alr_environment = { path='../../..' }

[[depends-on]]
ada_lib_base = "~0.1.0-dev"

[[pins]]
ada_lib_base = { path='../../../ada_lib/ada_lib_base' }

[[depends-on]]
gnoga_options = "~0.1.0-dev"

[[pins]]
gnoga_options = { path='../../../gnoga_lib/gnoga_options' }

[[depends-on]]
gnatcoll = "*"

